name: torchbox3d
channels:
  - conda-forge
dependencies:
  - av
  - av2
  - hydra-core
  - kornia
  - matplotlib-base
  - nox
  - numpy ==1.21.5
  - omegaconf
  - pandas
  - pip
  - pyarrow
  - python
  - pytorch ==1.11.0
  - pytorch-lightning
  - pyyaml
  - rich
  - s3fs
  - scipy
  - torchsparse
  - torchvision
