name: torchbox3d
channels:
  - conda-forge
dependencies:
  - av
  - av2
  - hydra-core
  - kornia
  - matplotlib-base
  - nox
  - numpy
  - omegaconf
  - pandas
  - pip
  - pyarrow
  - python
  - pytorch
  - pytorch-lightning
  - pyyaml
  - rich
  - scipy
  - tensorboard
  - torchsparse
  - torchvision
